
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: roots
    url: jdbc:mariadb://localhost:3309/batchs_practice?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        show_sql: true
        format_sql: true
        order_inserts: true   # 복수!
        order_updates: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 9093